-- BSB Stationery Data Import
-- Run this in SSMS AFTER setup_db.sql is done
USE BSBStationery;
GO

-- Clear any existing demo data (users are kept)
DELETE FROM IssueItems;
DELETE FROM IssueRecords;
DELETE FROM Items;
DELETE FROM SubCategories;
DELETE FROM ParentCategories;
GO

-- Parent category
INSERT INTO ParentCategories (Name) VALUES ('STATIONERY');
GO

DECLARE @pid INT = (SELECT ParentCatID FROM ParentCategories WHERE Name='STATIONERY');

-- Sub-categories
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('GENERAL STATIONARY', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('BOARD AND HANGING SUPPLIES', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('COLOURS', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('BATTERIES', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('MARKER', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('CALCULATORS', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('TAPE', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('Papers', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('DIVIDERS', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('Pens', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('HIGHLIGHTERS', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('Post it', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('CD/DVD', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('Envelopes', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('GLUE', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('Lamination Pouches', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('Clips', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('Notebook/Register', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('White Boards', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('Binding', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('Files', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('OFFICE SUPPLIES', @pid);
INSERT INTO SubCategories (Name, ParentCatID) VALUES ('STAPLE PINS', @pid);
GO

-- Items
DECLARE @sid INT;
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='GENERAL STATIONARY');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('HB PENCILS', @sid, 0, '12/BOX', 0.695, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('ERASERS (LARGE)', @sid, 0, 'EACH', 0.050, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('RUBBER BANDS -Size:18.-24 GM (Small)', @sid, 0, 'PER BOX', 0.130, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('RUBBER BANDS -Size:77.-100 GM (Big)', @sid, 0, 'PER BOX', 0.250, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('RULER/SCALE (30 CM)', @sid, 0, 'EACH', 0.175, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('RULER/SCALE (15 CM)', @sid, 0, '10/PKT', 0.100, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('SCISSORS LARGE-FOR TEACHER''S USE SDI 5835', @sid, 0, 'EACH', 0.360, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('SCISSORS SMALL-FOR STUDENTS'' USE HQT-539', @sid, 0, 'EACH', 0.175, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('SHARPENERS', @sid, 0, 'BOX/20', 1.080, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PROTRACTOR L09 15CM/360° HELIX', @sid, 0, 'EACH', 0.175, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('STICKY BACK PAPER - TO COVER BOOKS 10YDS', @sid, 0, 'PER ROLL', 0.980, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='BOARD AND HANGING SUPPLIES');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BOARD PINS', @sid, 0, '100/BOX', 0.175, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('SPLIT PINS', @sid, 0, 'Box of 25', 0.300, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BLUE TACK', @sid, 0, 'PKT', 0.395, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='COLOURS');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('COLOURED PENCILS-Faber Castell', @sid, 0, '12/BOX-PKT', 0.520, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('COLOURED FELT TIPPED PENS-Faber Castell', @sid, 0, '12/BOX', 0.500, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('CRAYONS (SMALL)-Faber Castell', @sid, 0, 'PKT/12', 0.700, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('CRAYONS (JUMBO)-Faber Castell', @sid, 0, 'PKT/12', 0.800, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('WATERCOLOUR PAINTS-Faber Castell', @sid, 0, 'EACH', 0.635, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='BATTERIES');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('AA BATTERIES', @sid, 0, 'PACK OF 1', 1.950, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('AAA BATTERIES', @sid, 0, 'PACK OF 1', 1.950, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('9 Volt Batteries Energizer Max 9V Battery 2pcs', @sid, 0, 'PACK OF 2', 3.850, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='MARKER');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BOARD MARKERS BLACK', @sid, 0, '12/BOX', 2.500, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BOARD MARKERS BLUE', @sid, 0, '12/BOX', 2.500, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BOARD MARKERS GREEN', @sid, 0, '12/BOX', 2.500, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BOARD MARKERS RED', @sid, 0, '12/BOX', 2.500, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PERMANENT MARKER POWERLINE PER-600 (BLACK)', @sid, 0, 'EACH', 0.210, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PERMANENT MARKER POWERLINE PER-600 (RED)', @sid, 0, 'EACH', 0.210, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='CALCULATORS');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('CASIO FX82MS SCIENTIFIC CALCULATORS', @sid, 0, 'EACH', 5.000, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('CASIO POCKET CALCULATOR SL-797', @sid, 0, 'EACH', 3.000, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('CASIO DM-1200T', @sid, 0, 'EACH', 4.500, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='TAPE');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('CELLOTAPE 1"', @sid, 0, 'EACH', 0.110, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('CELLOTAPE 1/2 "', @sid, 0, 'EACH', 0.150, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('CELLOTAPE 2"', @sid, 0, 'EACH', 0.255, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('DOUBLE SIDED MOUNTING TAPE', @sid, 0, 'EACH', 0.375, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('MASKING TAPE - WIDE', @sid, 0, 'EACH', 0.175, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('MASKING TAPE - NARROW', @sid, 0, 'EACH', 0.180, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='Papers');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PHOTOCOPY PAPER A3', @sid, 0, 'REAM', 2.900, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('CARD A3-WHITE', @sid, 0, 'PER REAM', 1.515, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('Card A3-BLACK', @sid, 0, 'PER REAM', 2.600, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PHOTOCOPY PAPER A4', @sid, 0, 'REAM', 1.200, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BRISTOL CARD A4 - PINK', @sid, 0, 'PER REAM', 0.940, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BRISTOL CARD A4 - BLUE', @sid, 0, 'PER REAM', 0.940, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BRISTOL CARD A4 - YELLOW', @sid, 0, 'PER REAM', 0.940, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BRISTOL CARD A4 - GREEN', @sid, 0, 'PER REAM', 0.940, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BRISTOL CARD A4 - BLACK', @sid, 0, 'PER REAM', 2.800, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BRISTOL CARD A4 - WHITE', @sid, 0, 'PER REAM', 0.940, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('COLOURED PAPER -RAINBOW 10COL 100SH/REAM', @sid, 0, 'PER REAM', 0.635, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('COLOURED PAPER - PINK', @sid, 0, 'PER REAM', 1.825, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('COLOURED PAPER - BLUE', @sid, 0, 'PER REAM', 1.825, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('COLOURED PAPER - YELLOW', @sid, 0, 'PER REAM', 1.825, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('COLOURED PAPER - GREEN', @sid, 0, 'PER REAM', 1.990, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('COLOURED PAPER - SINAR SPECTRA', @sid, 0, 'PKT/100', 0.500, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('TRACING PAPER A4 PAD', @sid, 0, 'PER PAD', 3.775, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('GLOSSY INKJET PHOTO PAPER 180GSM 20SHT', @sid, 0, 'BOX/20', 2.825, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('LABELS A4 SHEET', @sid, 0, 'PER BOX', 3.300, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('LABELS-16 SQUARES ON A PAGE 10-551012 2X8', @sid, 0, 'PER BOX', 4.400, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='DIVIDERS');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PAPER FILE DIVIDERS 1-12', @sid, 0, 'PER PACK', 1.200, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PAPER FILE DIVIDERS A-Z', @sid, 0, 'PER PACK', 1.500, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('DELI INDEX TABS-A118-02', @sid, 0, 'PER PACK(10X3)', 0.500, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('DELI INDEX TABS (Sign Here)-EA11302', @sid, 0, 'PER PACK(5 x 20 sheets)', 0.450, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='Pens');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BALLPEN(BLUE)', @sid, 0, '50/BOX', 1.750, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BALLPEN(BLACK)', @sid, 0, '50/BOX', 1.750, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BALLPEN(GREEN)', @sid, 0, '50/BOX', 1.750, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BALLPEN(RED)', @sid, 0, '50/BOX', 1.750, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('Uniball FINE (BLACK)', @sid, 0, '12/BOX', 3.995, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('Uniball FINE (BLUE)', @sid, 0, '12/BOX', 3.995, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('Uniball FINE (GREEN)', @sid, 0, '12/BOX', 3.995, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('Uniball FINE (RED)', @sid, 0, '12/BOX', 3.995, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('TIPPEX CORRECTOR PENS SDF-08', @sid, 0, 'EACH', 0.150, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='HIGHLIGHTERS');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('HIGHLIGHTER-GREEN', @sid, 0, '1X10', 1.350, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('HIGHLIGHTER-YELLOW', @sid, 0, '1X10', 1.350, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('HIGHLIGHTER-PINK', @sid, 0, '1X10', 1.350, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('HIGHLIGHTER-BLUE', @sid, 0, '1X10', 1.350, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='Post it');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('POST-IT 3X3"', @sid, 0, 'Pack of 6', 0.110, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('POST-IT 3X5"', @sid, 0, 'Pack of 6', 0.950, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('POST-IT 2X3"', @sid, 0, 'Pack of 6', 1.680, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='CD/DVD');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('DVD WRITE DISCS WITH COVER', @sid, 0, 'EACH', 0.190, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('CD WRITE DISC WITH COVER SONY', @sid, 0, 'EACH', 0.220, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='Envelopes');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('ENVELOPES A3 (SIZE 15" X 10") - USED FOR REPORT CARDS', @sid, 0, '250/BOX', 6.000, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('ENVELOPES A5', @sid, 0, '250/BOX', 4.000, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('ENVELOPE WHITE 12.75"X9" 100GSM ENVELORD', @sid, 0, '250/BOX', 7.500, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('ENVELOPE WHITE WPW 8.9"X4.5" 100GSM', @sid, 0, '250/BOX', 6.000, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('ENVELOPE WHITE 8.9"X4.5" 100GSM (WINDOW)', @sid, 0, '250/BOX', 6.500, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='GLUE');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('GLUE STICKS - 8GM', @sid, 0, 'EACH', 0.085, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('GLUE STICKS - 25GM', @sid, 0, 'EACH', 0.345, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PVA GLUE 120ML', @sid, 0, 'EACH', 0.330, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('GLUE STICKS FOR GLUE GUN', @sid, 0, 'Pack of 20', 0.500, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='Lamination Pouches');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('LAMINATION POUCHES - A3', @sid, 0, 'BOX/100', 5.800, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('LAMINATION POUCHES - A4', @sid, 0, 'BOX/100', 2.425, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('LAMINATION POUCHES - A5', @sid, 0, 'BOX/100', 2.000, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='Clips');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PAPER CLIPS SAX 233 - SMALL', @sid, 0, '100/BOX', 0.375, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PAPER CLIPS 236 - LARGE', @sid, 0, '100/BOX', 0.850, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BINDER CLIP-15MM', @sid, 0, '12/BOX', 0.325, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BINDER CLIP-25MM', @sid, 0, '12/BOX', 0.375, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BINDER CLIP-32MM', @sid, 0, '12/BOX', 0.400, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BINDER CLIP-51MM', @sid, 0, '12/BOX', 0.800, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='Notebook/Register');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('SHORTHAND NOTEBOOK 5"X8"', @sid, 0, 'EACH', 0.150, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('NOTE BOOK A4 (REGISTER A4 2QR)', @sid, 0, 'EACH', 0.575, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('Note Book A5', @sid, 0, 'EACH', 0.335, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='White Boards');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('WHITE BOARD CLEANER', @sid, 0, 'EACH', 1.200, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('WHITE BOARD DUSTER ER-Adult', @sid, 0, 'EACH', 0.160, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('WHITE BOARD DUSTER ER-INFANTS', @sid, 0, 'EACH', 0.300, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('WHITE BOARDS A4 25X35', @sid, 0, 'EACH', 0.800, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='Binding');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BINDING SHEET PAPER A3 230GSM 100SH/PKT (459) - WHITE', @sid, 0, '100/PACK', 3.000, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('BINDING SHEET PAPER A4 230GSM 100SH/PKT (459) - WHITE', @sid, 0, '100/PACK', 2.500, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('SPIRAL 10MM (I-BINDER WHITE/BLUE/BLACK)', @sid, 0, '100/PACK', 3.000, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('SPIRAL 12MM (I-BINDER WHITE/BLUE/BLACK)', @sid, 0, '100/PACK', 3.000, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('SPIRAL 14MM (FIS 14MM WHITE/BLUE/BLACK)', @sid, 0, '100/PACK', 3.000, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('SPIRAL 16MM (FIS 16MM WHITE/BLUE/BLACK)', @sid, 0, '100/PACK', 3.000, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PLASTIC SPINES - TO MAKE BOOKS 12MM', @sid, 0, 'PKT/100', 2.200, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='Files');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('A4 POCKETS - 11 PUNCHED HOLES 80MIC', @sid, 0, '100/BOX', 1.350, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('DOCUMENT WALLETS - CARDBOARD SADAF', @sid, 0, 'EACH', 0.095, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('HANGING FILES', @sid, 0, 'BOX/50', 0.350, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('LEVER ARCH FOLDERS - A4 BOX FILE-WIDE-3"', @sid, 0, 'EACH', 0.460, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('LEVER ARCH FOLDERS - A4 BOX FILE-NARROW-2"', @sid, 0, 'EACH', 0.485, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('LEVER ARCH FOLDERS - A5 BOX FILE', @sid, 0, 'EACH', 0.200, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('ZIP TOP WALLETS - A4 (DOCUMENT POUCH A4 )', @sid, 0, 'EACH', 0.500, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('ZIP TOP WALLETS - A3 (DOCUMENT POUCH A3 )', @sid, 0, 'EACH', 1.000, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PRESS STUD WALLET (A4)', @sid, 0, 'EACH', 0.135, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('A4 REPORT FOLDER -1 SIDE CLEAR FILE', @sid, 0, 'EACH', 0.090, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('FILE FASTENERS - METAL', @sid, 0, 'BOX', 0.475, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('TREASURY TAGS 8"', @sid, 0, 'BOX', 0.500, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('CLIP BOARD -A4', @sid, 0, 'EACH', 1.700, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='OFFICE SUPPLIES');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('STAPLES REMOVER', @sid, 0, 'EACH', 0.175, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('STAPLER DS-45', @sid, 0, 'EACH', 0.800, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('PAPER PUNCH DP-520 KANGARO', @sid, 0, 'NOS', 0.795, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('GUN TACKER (STAPLER GUN) TP-10R', @sid, 0, 'EACH', 6.875, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('TAPE DISPENSER 1" - DL-20032', @sid, 0, 'EACH', 0.550, 5);
SET @sid = (SELECT SubCatID FROM SubCategories WHERE Name='STAPLE PINS');
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('STAPLES 26/ 6 -5m-Kangaro', @sid, 0, 'BOX 5000/STAPLES', 0.080, 5);
INSERT INTO Items (Name, SubCatID, Quantity, Unit, UnitPrice, MinStock) VALUES ('STAPLES - SPECIFY SIZE: TR-13/10-(used for GUN TACKER)', @sid, 0, 'PKT', 0.500, 5);
GO

PRINT 'Imported 131 items across 23 categories!';
GO